CSCfi/kielipankki-nlf-harvester

.github/workflows/unit-test-python.yml
This required removing installations using yum, as we don't have root access. Installing python3 and pip3 are now done when preparing the container image instead.
=> KP-5793 Make the workflow compatible with Rahti

README.md, harvester/file.py, harvester/mets.py, harvester/pmh_interface.py, harvester/utils.py, harvester_cli.py, tests/conftest.py, tests/harvester/test_file.py, tests/harvester/test_mets.py, tests/harvester/test_pmh_interface.py, tests/harvester/test_utils.py, tests/test_harvester_cli.py
Add machinery for downloading files.
As an attempt for sane defaults, the default download location is constructed from `base_path`, `file_dir` and `file_name`, the defaults of which are set in the following manner:
```
./downloads/[filetype dependent directory]/[filename from location_xlink]
^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
base_path             file_dir                      file_name
```
which can result in e.g. `./downloads/1234/alto/00002.xml` for an ALTO file from binding 1234.
Each part can be overridden separately to e.g. keep the subdirectory structure but change the base path.
=> KP-6162 Implement downloading of files

harvester/file.py, tests/conftest.py, tests/harvester/test_file.py
Fixed the extraction of file paths from METS files (the previous logic was too restrictive) and added logic to extract ALTO paths for download URLs, when the path listed in METS does not follow the expected convention and results in a broken download URL.
I tested this by downloading ALTOs for one DC identifier for each collection available from the API. Testing did not reveal any issues with the path formation logic.
=> KP-6520 Hack ALTO file paths for download links

README.md, pipeline/requirements.txt
Previously there were identical requirements.txt files in the repository root and in the pipeline directory. Now the one in the one in the pipeline directory defines the pipeline-specific requirements. This is handy because now we don't need to sprinkle hard-coded requirements into Ansible roles.
This is required for https://github.com/CSCfi/Kielipankki/pull/69/commits/63c2ca28ae8ccf24f5a7873bdae86c1c012d0f4a.
=> KP-6211 Specify requirements for Airflow pipeline too

pipeline/dags/download_all_sets.py, pipeline/plugins/operators/custom_operators.py, pipeline/requirements.txt
Some changes to enable the download of all available collections from NLF with the current download logic (not depth-first and not parallelized).
=> KP-6568 Fixes to enable download of all available collections

harvester/file.py, pipeline/dags/download_all_altos.py, pipeline/plugins/operators/custom_operators.py, tests/conftest.py
I will add necessary hacks to make ALTO download possible as I encounter more issues.
ALTO filename creation is also updated based on new information from NLF (all filenames in ALTO download URLs are of type `n.xml`, so no preceding zeros need to be preserved, which simplified the code a bit.
=> Fixes for breadth-first ALTO download

pipeline/dags/parallel_download.py, pipeline/plugins/operators/custom_operators.py, tests/pipeline/test_custom_operators.py
Before METS or ALTO files are downloaded, it is checked if a non-empty file already exists in the path. Checking if the file exists already and skipping its download is 20-30% faster than redownloading the file.
Temporary code in `parallel_download` where DC identifiers for a set are read from a file is now commented out thanks to fixes to the NLF API.
=> KP-6842 Skip download of existing non-empty files

harvester/utils.py, harvester_cli.py, pipeline/dags/parallel_batch_download.py, pipeline/plugins/operators/custom_operators.py, tests/harvester/test_file.py, tests/harvester/test_pmh_interface.py, tests/harvester/test_utils.py, tests/pipeline/test_custom_operators.py
Directory structure for downloaded bindings is now as follows (for binding `1911598` in `col-361`):
`col-361/1/19/191/1911/19115/191159/1911598/1911598`.
Another depth for the directory structure can be set as well (e.g. 3):
`col-361/1/19/191/1911598`
=> KP-7021 Construct subdirectory structure

ansible/README.md, ansible/group_vars/all, ansible/roles/harvester-setup/tasks/main.yml
To make testing changes easier on harvester-dev, added option to provision DAGs from a specific branch in GitHub. It is also now possible to only provision the DAGs, which speeds up the provisioning process and eliminates the need to provide password store credentials etc.
=> Allow provisioning DAGs only, and from a specific branch

.pylintrc, harvester/utils.py, pipeline/dags/download_images.py, pipeline/dags/download_single_binding.py, pipeline/dags/fetch_binding_ids.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py, tests/harvester/test_file.py, tests/harvester/test_pmh_interface.py, tests/harvester/test_utils.py, tests/pipeline/test_custom_operators.py
Before making functional changes for https://github.com/CSCfi/kielipankki-nlf-harvester/pull/29, I wanted to do some refactoring. 
Most prominently I unified representing paths. Previously some paths were strings and some Paths, which added cognitive load to working with the code. Now using Paths everywhere (except when a string is explicitly needed, and then converting as late as possible) to unify the practice. Alternatively the types could have been specified in the docstrings, but that felt like more work and as it would have required following call chains pretty far at some cases, it would also likely have been more error-prone. Thus unifying to Paths was chosen.
Unused local download operators were removed.
I also opted to follow some pylint recommendations that have real effects on …
=> KP-7389 Refactoring before functional changes

pipeline/dags/download_images.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py, tests/pipeline/test_custom_operators.py
This PR reduces the load on Lustre and improves disk image creation performance by downloading the individual files to `local_scratch` instead of `scratch` on Puhti. The resulting disk images are written directly to the final location on scratch because the quota on local_scratch is not sufficient.
There are also some other improvements, e.g. adding safeguards that prevent creating images that contain .tmp files. Details in commits and commit messages.
=> KP-7389 Download individual files to fast local disk instead of lustre

harvester/utils.py, pipeline/dags/download_images.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py, tests/harvester/test_pmh_interface.py, tests/pipeline/test_custom_operators.py
This PR does not alter the functionality of the DAG. Instead, it contains refactoring, mostly concentrated around how paths to various files and directories are handled along the chain of tasks and operators.
First of all, the global configuration variables and their corresponding taks/operator arguments were renamed to be more descriptive. Now it is hopefully more clear what each of them means and the same term means the same thing everywhere.
Then, path construction was moved to higher level from the actual download operators. This brings us closer to having one authoritative source for information as opposed to e.g. METS and ALTO downloading operators constructing the same METS path individually, which is prone to cause trouble if we change the logic.
=> KP-7389 post-refactoring

ansible/group_vars/all, ansible/harvesterPouta.yml, ansible/inventories/dev, ansible/roles/airflow-requirements/tasks/main.yml, ansible/roles/harvester-setup/tasks/main.yml, ansible/roles/harvester-setup/templates/restic_env.yaml.j2, ansible/roles/restic-script-to-puhti/files/create_snapshot.sh, ansible/roles/restic-script-to-puhti/tasks/main.yml, pipeline/dags/download_images.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py
Added a task that automatically creates a snapshot of the freshly downloaded `squashfs` images. Additionally, fixed connecting to Puhti for key adding and fixed the Airflow installation URL that was recently updated.
The task assumes that there's an existing script  `create_snapshot.sh` in the home directory of our robot account, which there is. Not sure if it would be overkill to add an ansible task that makes sure that such script actually exists. At least it currently does and I don't see any reason why it would get deleted.
=> KP-6678 Create restic snapshot to allas after each download

ansible/requirements_dev.txt
Installing collections from git repositories requires at least version 2.10. With older versions we get
```
$ ansible-galaxy collection install -r requirements.yml
Process install dependency map
ERROR! Invalid collection name 'git@github.com:CSCfi/Kielipankki-ansible-common.git', name must be in the format <namespace>.<collection>.
```
instead.
=> Bump minimum Ansible version requirement

.pytest.ini, Makefile, pipeline/dags/download_single_binding.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py, pipeline/plugins/operators/file_download_operators.py, requirements_dev.txt, tests/pipeline/conftest.py, tests/pipeline/test_custom_operators.py
The `custom_operators` module was getting quite pönäccä, so instead of just stuffing more operators in, I split it into two: operators that take care of downloading a single file in one module, and other operators in other. This leads to a split that is not too far from 50/50 (especially considering that `file_download_operators` will get a new operator later in this ticket).
This also seemed like the most obvious group of operators that belong together. It is possible that there are other coherent sets of operators that could have their own module, but the scope in this PR was limited to the operators handled in this ticket, partially to avoid conflicts with other tickets under construction at the moment.
The operators were not altered in any way during the process, so functionality …
=> KP-6210 split operator module

harvester/file.py, pipeline/plugins/operators/custom_operators.py, pipeline/plugins/operators/file_download_operators.py, tests/conftest.py, tests/data/exotic_files_METS.xml, tests/harvester/test_file.py, tests/harvester/test_mets.py, tests/pipeline/test_file_download_operators.py
Using the extensibility enhancements from https://github.com/CSCfi/kielipankki-nlf-harvester/pull/49, this PR adds the new operator for downloading access images and incorporates it into the pipeline.
Access images are downloaded for each binding after ALTOs. Only METS file is required for a binding for access image download to be attempted: even if one or more ALTOs cannot be downloaded, access image download is attempted.
Now that we download both ALTO and access image files, we should no longer have "unaccounted" file types. Thus specific file groups (e.g. thumbnails, PDFs and target images) were explicitly set to be skipped, and if we encounter an unknown fileGrp ID/USE combination, an exception is raised. This shields us from accidentally skipping files that should be downloaded, as …
=> KP-6210 Download access images

ansible/README.md, ansible/inventories/prod, ansible/inventories/small-test, ansible/roles/harvester-setup/tasks/main.yml, pipeline/dags/fetch_binding_ids.py
Observed and fixed the following things before or during provisioning the new prod:
- Made the prod inventory syntactically correct
- Added option to reprovision DAGs only without reinstalling/updating installed software
- Remove the old collections from `fetch_binding_ids` DAG: no need to get the binding IDs as we don't intend to download them
=> KP-7716 Misc life quality improvements and fixes

ansible/group_vars/all, ansible/roles/airflow-config/defaults/main.yml, ansible/roles/airflow-config/templates/airflow.cfg.j2, ansible/roles/harvester-setup/templates/restic_env.yaml.j2, harvester/utils.py, tests/harvester/test_utils.py
Batches of >=100 cause tasks to never finish if they have large bindings, because the scheduler will run out of memory before the task completes. Reduced the batch size so that it, combined with provisioning a beefier VM to run on, will hopefully let us finish a download that contains page images too.
I also made the collection vs subset naming more consistent: the utility functions that are only used with subsets no longer talk about collections.
=> KP-7716 Fixes for doing the image run

harvester/file.py, harvester/mets.py, harvester_cli.py, pipeline/dags/download_collections.py, pipeline/dags/fetch_binding_ids.py, tests/conftest.py, tests/data/exotic_files_METS.xml, tests/harvester/test_file.py, tests/harvester/test_mets.py, tests/pipeline/test_file_download_operators.py, tests/test_harvester_cli.py
TL;DR:
- download URLs now based on page number, derived from SEQ attribute of   access image elements
- ALTOs created by creating an ALTO counterpart for each access image
- File naming changed: we now have 00001.xml and 00001.jp2 as opposed to  00001.xml and pr-00001.jp2
- No longer verifying that there are no unexpected file groups (none were found during the [KP-7716](https://jira.eduuni.fi/browse/KP-7716) run
Previously the download URLs for both ALTO and access image files were determined based on the file name in the METS file: e.g. image with file name "pr-00003.jp2" would get a download URL ending "/image/3". Unfortunately this does not always work, as there can be other files (target images etc) listed in METS with lower-numbered file names, or even file names between the actual …
=> KP-7610 Using SEQ attribute to determine page download URLs

docs/versioning.md
The slowness issue between Puhti and Allas when using restic has been fixed, so we can enforce accessing the backups from Puhti again. Removed the warnings urging not to do so and added Puhti-specific tips (e.g. choosing between scratch and tmpdir).
=> Encourage using Puhti with restic again

ansible/README.md, ansible/group_vars/all, ansible/inventories/dev, ansible/inventories/prod, ansible/roles/harvester-setup/defaults/main.yml, ansible/roles/harvester-setup/tasks/main.yml, ansible/roles/harvester-setup/templates/airflow_variables.json.j2, ansible/roles/restic-script-to-puhti/tasks/main.yml, pipeline/dags/download_collections.py, pipeline/dags/fetch_binding_ids.py, pipeline/plugins/includes/tasks.py
Previously, we needed to manually adjust the DAGs in dev environments to avoid overwriting production data. Now the provisioning script should produce properly configured environments depending on the inventory. This covers the following aspects:
- Temporary files needed during creation of the published zips
- Published zips
- Restic backup creation script
- Restic bucket used for versioning
Some additional improvements were also done:
- Possibility to set `initial_download` when provisioning or later in the GUI
- Possibility to configure the number of retries (default was lowered to 1 as genuine network problems haven't seemed common)
Customizing the DAGs for different environments has now been done using [variables](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/vari …
=> KP-7310 Proper configuration when provisioning dev/prod

ansible/reset.yml
Without providing the host and host bucket, s3cmd defaults to Amazon if there is no config file available, so the deletion command naturally fails. Including the necssary parameters in both means that the deletion should not fail any more.
=> KP-9953 Fix reset failing if there's no s3cmd config file

ansible/roles/harvester-setup/defaults/main.yml, ansible/roles/harvester-setup/templates/airflow_variables.json.j2, harvester/pmh_interface.py, harvester/utils.py, harvester_cli.py, pipeline/dags/download_collections.py, pipeline/dags/fetch_binding_ids.py, pipeline/plugins/includes/tasks.py, pipeline/plugins/operators/custom_operators.py, tests/harvester/test_utils.py
Deleted records can be listed based on collection and start of a date range.
The records are parsed from
https://digi.kansalliskirjasto.fi/interfaces/OAI-PMH?verb=ListRecords&metadataPrefix=oai_dc&set=deleted by filtering by collection and date instead of using searches such as https://digi.kansalliskirjasto.fi/interfaces/OAI-PMH?verb=ListIdentifiers&metadataPrefix=oai_dc&set=col-501&from=2025-03-01 and filtering for `status="deleted"`. This is done because the latter does not always include all records present in the former. For example th e latter says `<error code="noRecordsMatch">No records found with the given parameters.</error>` at the time of writing, while the former clearly lists
```
<record>
<header status="deleted">
<identifier>oai:digi.kansalliskirjasto.fi:3002584</identifier> …
```
=> KP-6519 Deleted bindings

pipeline/plugins/includes/tasks.py
Firstly, the f-string that contained the path to the zips wasn't an f-string, but a normal string.
Secondly, when changed to an f-string, it still contained {} which were not string interpolations, so they needed to be changed into {}.
Thirdly, and most confusingly, it's possible to read from the stdout channel of the ssh client after the connection has been closed, but it won't contain anything. So let's read it before leaving the client context.
=> KP-10312 Fix three bugs in zip-listing command
